NaN pulse widths are unexpectedly causing problems.
self.ser.write(bytes(str(int(pulse_width)) + n, UTF-8))
ValueError: cannot convert float NaN to integer

This line hasn't changed, nor has, AFAICT, the calculation of pulse_width,
so I don't understand this error.

This commit slaps a band aid on the problem, but gotta keep an eye on it.