Error message for TB power issue, TB ino noise update (#71)
More useful error message when encountering TB power issue.

TB ino update from Kate to "generate 56Hz noise instead of 64 Hz noise."

* NaN pulse widths are unexpectedly causing problems.

self.ser.write(bytes(str(int(pulse_width)) + n, UTF-8))
ValueError: cannot convert float NaN to integer

This line hasn't changed, nor has, AFAICT, the calculation of pulse_width,
so I don't understand this error.

This commit slaps a band aid on the problem, but gotta keep an eye on it.

* Catch Nan pulse width, restore 56Hz noise.

Nans can be cast to float, but more usefully, let's just catch the bad
number and give an error message.

To the arduino code: previous version erroneously caused 64Hz noise. I
do not know to what noise Kate is referring.